import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useEffect } from 'react'
import { useSelector } from 'react-redux'
import Navbar from '../../components/Navbar'
import Post from '../../components/Post'
import Search from '../../components/Search'
import SideBar from '../../components/SideBar'

const postPage = () => {
  const router = useRouter();
  const {currentUser} = useSelector(state=>state.auth);

  useEffect(()=>{
      if(!currentUser){
          router.replace('/login')
      }
  },[currentUser])
  return (
    <div>
      <Head>
        <title>Share Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar />
      <div className='flex'>
        <SideBar />
        <div className='flex-1 px-8 py-3  ml-0 md:ml-[220px]'>
          <Search />
         <Post currentUser={currentUser}/>
        </div>
      </div>
    </div>
  )
}

export default postPage
