import Head from 'next/head'
import SideBar from '../components/SideBar'
import { useEffect } from 'react';
import Posts from '../components/Posts';
import Search from '../components/Search';
import Navbar from '../components/Navbar';
import { useSelector,useDispatch } from 'react-redux';
import { getposts } from '../redux/slices/postsSclice';
import { useRouter } from 'next/router';


export default function Home() {
  let router = useRouter()
  let {category} = router.query;
   let {posts} = useSelector(state=>state.posts)
   let dispatch = useDispatch()
    const {currentUser} = useSelector(state=>state.auth);

    useEffect(()=>{
        if(!currentUser){
            router.replace('/login')
        }
    },[currentUser])

   console.log(category)
   useEffect(()=>{
    dispatch(getposts(category));
   },[category])
  return (
    <div>
      <Head>
        <title>Share Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar />
      <div className='flex'>
        <SideBar />
        <div className='flex-1 px-8 py-3 ml-0 md:ml-[220px]'>
          <Search />
         <Posts posts={posts}/>
        </div>
      </div>
    </div>
  )
}
