import React from 'react'
import Head from 'next/head';
import {  getAuth, signInWithPopup,GoogleAuthProvider } from "firebase/auth";
import {app} from '../firebase';
import axios from 'axios';
import { useDispatch } from 'react-redux';
import { logIn } from '../redux/slices/authSlice';
import { useRouter } from 'next/router';

const signin = () => {
  let dispatch = useDispatch();
  let router = useRouter()
  const  signWithGoogle=()=>{
    const provider = new GoogleAuthProvider();
    const auth = getAuth(app);
    signInWithPopup(auth, provider)
      .then((result) => {

        // The signed-in user info.
        const user = {
          name:result.user.displayName,
          email:result.user.email,
          avatar:result.user.photoURL
        }
        axios.get(`http://localhost:5000/users/?email=${user.email}`)
        .then(getres=>{
          if(getres.data.length==0){
            axios.post(`http://localhost:5000/users`,user)
            .then(postres=>{
              dispatch(logIn(postres.data))
            }).catch(console.log)
          }else{
            console.log(getres.data[0])
            dispatch(logIn(getres.data[0]))

          }
          router.replace('/');

        }).catch(console.log)
        
      }).catch((err) => {
        console.log(err)

      });
  }
  return (
    <div>
      <Head>
        <title>Share Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      
      <div className='flex items-center justify-center min-h-screen'>
        <div className='max-w-lg'>
          <button onClick={signWithGoogle} className='rounded-md border-solid border-2 p-1 border-slate-700 bg-red-600 text-white'>sign in with google</button>
        </div>
      </div>
    </div>
  )
}

export default signin
